"""Add all models

Revision ID: 3e6ed57b1e3b
Revises: dc1e6a5cef59
Create Date: 2025-07-27 21:25:45.855530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e6ed57b1e3b'
down_revision: Union[str, Sequence[str], None] = 'dc1e6a5cef59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('area_of_activity', sa.String(length=500), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('pre_requisites', sa.Text(), nullable=True),
    sa.Column('differentials', sa.Text(), nullable=True),
    sa.Column('code_vacancy_job', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_code_vacancy_job'), 'jobs', ['code_vacancy_job'], unique=True)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_name'), 'jobs', ['job_name'], unique=False)
    op.create_table('academic_backgrounds',
    sa.Column('academic_background_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('degree_name', sa.String(length=255), nullable=False),
    sa.Column('degree_type', sa.String(length=100), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('academic_background_id')
    )
    op.create_index(op.f('ix_academic_backgrounds_academic_background_id'), 'academic_backgrounds', ['academic_background_id'], unique=False)
    op.create_index(op.f('ix_academic_backgrounds_institution_name'), 'academic_backgrounds', ['institution_name'], unique=False)
    op.create_index(op.f('ix_academic_backgrounds_user_id'), 'academic_backgrounds', ['user_id'], unique=False)
    op.create_table('addresses',
    sa.Column('address_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('street_type', sa.String(length=50), nullable=True),
    sa.Column('street_name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_addresses_address_id'), 'addresses', ['address_id'], unique=False)
    op.create_index(op.f('ix_addresses_cep'), 'addresses', ['cep'], unique=False)
    op.create_index(op.f('ix_addresses_company_id'), 'addresses', ['company_id'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('curricula',
    sa.Column('curriculum_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_base64', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('is_work', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curriculum_id')
    )
    op.create_index(op.f('ix_curricula_curriculum_id'), 'curricula', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_curricula_file_name'), 'curricula', ['file_name'], unique=True)
    op.create_index(op.f('ix_curricula_user_id'), 'curricula', ['user_id'], unique=False)
    op.create_table('professional_courses',
    sa.Column('professional_courses_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('duration_time_hours', sa.Integer(), nullable=True),
    sa.Column('certification_media_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('certification_media_image', sa.LargeBinary(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_courses_id')
    )
    op.create_index(op.f('ix_professional_courses_institution_name'), 'professional_courses', ['institution_name'], unique=False)
    op.create_index(op.f('ix_professional_courses_professional_courses_id'), 'professional_courses', ['professional_courses_id'], unique=False)
    op.create_index(op.f('ix_professional_courses_user_id'), 'professional_courses', ['user_id'], unique=False)
    op.create_table('professional_experiences',
    sa.Column('professional_experience_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_experience_id')
    )
    op.create_index(op.f('ix_professional_experiences_company_name'), 'professional_experiences', ['company_name'], unique=False)
    op.create_index(op.f('ix_professional_experiences_professional_experience_id'), 'professional_experiences', ['professional_experience_id'], unique=False)
    op.create_index(op.f('ix_professional_experiences_user_id'), 'professional_experiences', ['user_id'], unique=False)
    op.create_table('professional_profiles',
    sa.Column('professional_profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('professional_profile_name', sa.String(length=255), nullable=False),
    sa.Column('professional_profile_description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('academic_background_id', sa.UUID(), nullable=True),
    sa.Column('professional_experience_id', sa.UUID(), nullable=True),
    sa.Column('professional_courses_id', sa.UUID(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_profile_id')
    )
    op.create_index(op.f('ix_professional_profiles_professional_profile_id'), 'professional_profiles', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_professional_profiles_user_id'), 'professional_profiles', ['user_id'], unique=False)
    op.create_table('analyze_application_jobs',
    sa.Column('analyze_application_job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('professional_experience_score', sa.Float(), nullable=True),
    sa.Column('professional_courses_score', sa.Float(), nullable=True),
    sa.Column('weak_points_score', sa.Float(), nullable=True),
    sa.Column('strong_points_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('opinion_application_job', sa.Text(), nullable=True),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.professional_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analyze_application_job_id')
    )
    op.create_index(op.f('ix_analyze_application_jobs_analyze_application_job_id'), 'analyze_application_jobs', ['analyze_application_job_id'], unique=False)
    op.create_index(op.f('ix_analyze_application_jobs_professional_profile_id'), 'analyze_application_jobs', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_analyze_application_jobs_total_score'), 'analyze_application_jobs', ['total_score'], unique=False)
    op.create_index(op.f('ix_analyze_application_jobs_user_id'), 'analyze_application_jobs', ['user_id'], unique=False)
    op.create_table('application_jobs',
    sa.Column('application_job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.professional_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_job_id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_application')
    )
    op.create_index(op.f('ix_application_jobs_application_job_id'), 'application_jobs', ['application_job_id'], unique=False)
    op.create_index(op.f('ix_application_jobs_job_id'), 'application_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_jobs_professional_profile_id'), 'application_jobs', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_application_jobs_user_id'), 'application_jobs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('users_user_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.drop_column('users', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.create_unique_constraint(op.f('users_user_email_key'), 'users', ['user_email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'updated_date')
    op.drop_index(op.f('ix_application_jobs_user_id'), table_name='application_jobs')
    op.drop_index(op.f('ix_application_jobs_professional_profile_id'), table_name='application_jobs')
    op.drop_index(op.f('ix_application_jobs_job_id'), table_name='application_jobs')
    op.drop_index(op.f('ix_application_jobs_application_job_id'), table_name='application_jobs')
    op.drop_table('application_jobs')
    op.drop_index(op.f('ix_analyze_application_jobs_user_id'), table_name='analyze_application_jobs')
    op.drop_index(op.f('ix_analyze_application_jobs_total_score'), table_name='analyze_application_jobs')
    op.drop_index(op.f('ix_analyze_application_jobs_professional_profile_id'), table_name='analyze_application_jobs')
    op.drop_index(op.f('ix_analyze_application_jobs_analyze_application_job_id'), table_name='analyze_application_jobs')
    op.drop_table('analyze_application_jobs')
    op.drop_index(op.f('ix_professional_profiles_user_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_professional_profile_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index(op.f('ix_professional_experiences_user_id'), table_name='professional_experiences')
    op.drop_index(op.f('ix_professional_experiences_professional_experience_id'), table_name='professional_experiences')
    op.drop_index(op.f('ix_professional_experiences_company_name'), table_name='professional_experiences')
    op.drop_table('professional_experiences')
    op.drop_index(op.f('ix_professional_courses_user_id'), table_name='professional_courses')
    op.drop_index(op.f('ix_professional_courses_professional_courses_id'), table_name='professional_courses')
    op.drop_index(op.f('ix_professional_courses_institution_name'), table_name='professional_courses')
    op.drop_table('professional_courses')
    op.drop_index(op.f('ix_curricula_user_id'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_file_name'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_curriculum_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_company_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_cep'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_academic_backgrounds_user_id'), table_name='academic_backgrounds')
    op.drop_index(op.f('ix_academic_backgrounds_institution_name'), table_name='academic_backgrounds')
    op.drop_index(op.f('ix_academic_backgrounds_academic_background_id'), table_name='academic_backgrounds')
    op.drop_table('academic_backgrounds')
    op.drop_index(op.f('ix_jobs_job_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_code_vacancy_job'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
