"""Fix all relationships

Revision ID: 4f5b463edeb8
Revises: 3e6ed57b1e3b
Create Date: 2025-07-27 22:31:50.271391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5b463edeb8'
down_revision: Union[str, Sequence[str], None] = '3e6ed57b1e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyze_application_jobs', sa.Column('application_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_analyze_application_jobs_application_job_id'), 'analyze_application_jobs', ['application_job_id'], unique=False)
    op.create_foreign_key(None, 'analyze_application_jobs', 'application_jobs', ['application_job_id'], ['application_job_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyze_application_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_analyze_application_jobs_application_job_id'), table_name='analyze_application_jobs')
    op.drop_column('analyze_application_jobs', 'application_job_id')
    # ### end Alembic commands ###
