"""Initial

Revision ID: bba80e9d40d5
Revises: 
Create Date: 2025-07-23 23:57:40.579533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba80e9d40d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('is_work', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=255), nullable=False),
    sa.Column('professional_profile_id', sa.UUID(), nullable=True),
    sa.Column('professional_experience_id', sa.UUID(), nullable=True),
    sa.Column('professional_courses_id', sa.UUID(), nullable=True),
    sa.Column('academic_background_id', sa.UUID(), nullable=True),
    sa.Column('analyze_application_job_id', sa.UUID(), nullable=True),
    sa.Column('curriculum_id', sa.UUID(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('birth_day', sa.Date(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
